version: '2.1'

# Running Kafka and zookeeper in a docker container

services:
  kafka:
    image: wurstmeister/kafka
    mem_limit: 400m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    container_name: kafka

  zookeeper:
    image: wurstmeister/zookeeper
    mem_limit: 400m
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
    container_name: zookeeper

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    mem_limit: 400m
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    container_name: rabbitmq
    # Enable the web management page on port 15672 : http://127.0.0.1/15672 Username: guest, Password: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 10